In [23]:
import scipy.io
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
file_path = "balanced_snow_dictionary.mat"
mat_data = scipy.io.loadmat(file_path)
matrix_data = mat_data['dic_snow'] # for others use dic_land, dic_ice, dic_ocean, dic_coast, dic_sc

# Convert the matrix data to a Pandas DataFrame
df = pd.DataFrame(matrix_data) # load dictionary for different surface type and store it into differet dataframe

In [24]:
rows_to_keep = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 29] # I have put the input features in the rows
#and only the rows with given rows index will be used for our model
df_req = df.iloc[rows_to_keep]
df_req

,0,1,2,3,4,5,6,7,8,9,...,226064,226065,226066,226067,226068,226069,226070,226071,226072,226073
0,255.639999,239.979996,204.830002,265.230011,235.339996,256.470001,254.759995,251.520004,246.389999,248.279999,...,237.570007,237.570007,237.570007,237.570007,237.570007,237.039993,237.039993,237.039993,237.039993,235.539993
1,250.630005,227.750000,153.820007,256.390015,211.279999,240.289993,251.330002,239.800003,237.270004,226.759995,...,196.479996,196.479996,196.479996,196.479996,196.479996,196.169998,196.169998,196.169998,196.169998,200.500000
2,253.729996,236.039993,222.539993,262.309998,233.990005,256.019989,254.759995,248.380005,251.020004,239.470001,...,249.240005,249.240005,249.240005,249.240005,249.240005,248.509995,248.509995,248.509995,248.509995,246.389999
3,249.339996,225.559998,177.339996,253.770004,211.039993,235.720001,251.660004,238.699997,241.169998,212.699997,...,216.559998,216.559998,216.559998,216.559998,216.559998,216.389999,216.389999,216.389999,216.389999,216.740005
4,252.610001,232.889999,228.270004,260.359985,233.949997,248.789993,253.449997,238.699997,251.360001,227.639999,...,257.010010,257.010010,257.010010,257.010010,257.010010,255.990005,255.990005,255.990005,255.990005,254.399994
5,248.429993,213.940002,236.960007,243.889999,236.399994,223.500000,252.059998,213.910004,247.660004,202.910004,...,259.549988,259.549988,259.549988,259.549988,259.549988,259.980011,259.980011,259.980011,259.980011,259.070007
6,244.369995,205.410004,203.460007,236.509995,218.289993,209.440002,248.679993,207.289993,239.080002,185.789993,...,244.410004,244.410004,244.410004,244.410004,244.410004,243.429993,243.429993,243.429993,243.429993,243.220001
7,231.539993,184.380005,244.929993,214.020004,241.789993,206.919998,240.149994,219.669998,224.089996,196.520004,...,267.809998,267.809998,267.809998,267.809998,267.809998,267.690002,267.690002,267.690002,267.690002,267.070007
8,227.869995,179.220001,221.339996,209.669998,225.910004,197.149994,237.270004,215.750000,219.149994,184.669998,...,265.950012,265.950012,265.950012,265.950012,265.950012,266.160004,266.160004,266.160004,266.160004,264.980011
9,229.660004,205.770004,237.380005,236.820007,231.800003,213.139999,240.320007,224.720001,231.990005,204.850006,...,265.230011,265.230011,265.230011,265.230011,265.230011,264.089996,264.089996,264.089996,264.089996,265.750000
10,227.449997,202.339996,224.649994,233.929993,221.460007,205.639999,236.610001,220.320007,229.210007,196.669998,...,265.339996,265.339996,265.339996,265.339996,265.339996,265.570007,265.570007,265.570007,265.570007,265.679993
11,248.059998,250.690002,250.509995,256.519989,247.389999,254.660004,250.539993,250.389999,259.209991,242.279999,...,253.050003,253.050003,253.050003,253.050003,253.050003,253.339996,253.339996,253.339996,253.339996,252.820007
12,243.210007,241.600006,245.039993,256.859985,237.630005,235.899994,250.679993,246.089996,254.750000,227.639999,...,260.029999,260.029999,260.029999,260.029999,260.029999,259.929993,259.929993,259.929993,259.929993,260.690002
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
29,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df_req.iloc[13].unique() # This rows give information about precipitation phase. 0 = no_precip, 3= rain, 5= snow

array([0., 5., 3.])

In [26]:
df_req.iloc[13] = df_req.iloc[13].replace({3.0: 1, 5.0: 2}) # Modifying the index so 1 = rain, 2=snow
# we are providing the name to the input features. They are the information measured by the differnt frequencies that
# helps to determine the precipitation phase
variables = ['10v_BT', '10h_BT', '18v_BT', '18h_BT', '23v_BT', '36v_BT', '36h_BT', '89v_BT', '89h_BT', '166v_BT', '166h_BT', '183-3_BT','183-7_BT', 'precip_flag','pr_rate_nearSurf']
df_req.loc[:, 'variable'] = variables
df_req.set_index('variable', inplace=True)
# If you find missing data, delete the entire column. If the data of one input feature is missing, data of other features at
#that instant is of no use
df_req = df_req.dropna(axis=1)
#I am transposing it for the proper visualization
df_tran = df_req.T
df_tran

variable,10v_BT,10h_BT,18v_BT,18h_BT,23v_BT,36v_BT,36h_BT,89v_BT,89h_BT,166v_BT,166h_BT,183-3_BT,183-7_BT,precip_flag,pr_rate_nearSurf
6,254.759995,251.330002,254.759995,251.660004,253.449997,252.059998,248.679993,240.149994,237.270004,240.320007,236.610001,250.539993,250.679993,0.0,0.000000
10,255.580002,251.339996,250.500000,246.070007,247.669998,242.619995,238.940002,221.389999,218.960007,226.850006,224.360001,243.429993,241.570007,0.0,0.000000
13,251.460007,246.149994,248.779999,242.850006,246.360001,235.919998,232.550003,209.850006,206.149994,229.669998,227.179993,250.470001,250.710007,0.0,0.000000
14,249.789993,239.399994,237.009995,224.710007,225.130005,199.369995,189.289993,187.610001,182.259995,207.550003,203.240005,245.270004,242.509995,0.0,0.000000
16,254.740005,235.369995,245.130005,224.149994,239.809998,221.059998,204.479996,196.240005,185.350006,213.929993,206.419998,248.830002,240.479996,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226059,204.389999,159.839996,220.679993,179.509995,235.479996,238.970001,206.800003,258.570007,246.070007,261.459991,256.880005,248.710007,256.019989,1.0,0.340050
226060,204.389999,159.839996,220.679993,179.509995,235.479996,238.970001,206.800003,258.570007,246.070007,261.459991,256.880005,248.710007,256.019989,1.0,0.340050
226061,204.389999,159.839996,220.679993,179.509995,235.479996,238.970001,206.800003,258.570007,246.070007,261.459991,256.880005,248.710007,256.019989,1.0,0.340050
226062,204.389999,159.839996,220.679993,179.509995,235.479996,238.970001,206.800003,258.570007,246.070007,261.459991,256.880005,248.710007,256.019989,1.0,0.325864
226063,204.389999,159.839996,220.679993,179.509995,235.479996,238.970001,206.800003,258.570007,246.070007,261.459991,256.880005,248.710007,256.019989,1.0,0.325864

Now, you can start training the model. Create the datafrmae like this for the different surface type and evaluate the classifiers for each surface type. At the last, you can concatenate all the dataframe and can train the model on the whole data at once and see whether land surface classification increase model performance or not.

## Here is the Demo code that shows you How I trained xtreme gradient boosting decision tree for the phase prediction

In [33]:
pip install numpy

Requirement already satisfied: numpy in c:\users\aryan\anaconda3\lib\site-packages (1.26.4)
Note: you may need to restart the kernel to use updated packages.

In [34]:
pip install pandas

Requirement already satisfied: pandas in c:\users\aryan\anaconda3\lib\site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\aryan\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aryan\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\aryan\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\aryan\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\aryan\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [35]:
pip install seaborn

Requirement already satisfied: seaborn in c:\users\aryan\anaconda3\lib\site-packages (0.12.2)
Requirement already satisfied: numpy!=1.24.0,>=1.17 in c:\users\aryan\anaconda3\lib\site-packages (from seaborn) (1.26.4)
Requirement already satisfied: pandas>=0.25 in c:\users\aryan\anaconda3\lib\site-packages (from seaborn) (2.1.4)
Requirement already satisfied: matplotlib!=3.6.1,>=3.1 in c:\users\aryan\anaconda3\lib\site-packages (from seaborn) (3.8.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\aryan\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\aryan\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\aryan\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\aryan\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\aryan\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (23.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\aryan\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\aryan\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\aryan\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\aryan\anaconda3\lib\site-packages (from pandas>=0.25->seaborn) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\aryan\anaconda3\lib\site-packages (from pandas>=0.25->seaborn) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\aryan\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.1->seaborn) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [36]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\aryan\anaconda3\lib\site-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in c:\users\aryan\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.3.2 in c:\users\aryan\anaconda3\lib\site-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in c:\users\aryan\anaconda3\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\aryan\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Note: you may need to restart the kernel to use updated packages.

In [37]:
pip install pydotplus

Requirement already satisfied: pydotplus in c:\users\aryan\anaconda3\lib\site-packages (2.0.2)
Requirement already satisfied: pyparsing>=2.0.1 in c:\users\aryan\anaconda3\lib\site-packages (from pydotplus) (3.0.9)
Note: you may need to restart the kernel to use updated packages.

In [38]:
pip install GraphViz

Requirement already satisfied: GraphViz in c:\users\aryan\anaconda3\lib\site-packages (0.20.1)
Note: you may need to restart the kernel to use updated packages.

In [39]:
pip install xgboost

Requirement already satisfied: xgboost in c:\users\aryan\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: numpy in c:\users\aryan\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\aryan\anaconda3\lib\site-packages (from xgboost) (1.11.4)
Note: you may need to restart the kernel to use updated packages.

In [27]:
# Now its time to train the model
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
X = df_tran[['10v_BT', '10h_BT', '18v_BT', '18h_BT', '23v_BT', '36v_BT', '36h_BT', '89v_BT', '89h_BT', '166v_BT', '166h_BT', '183-3_BT', '183-7_BT']]
y = df_tran['precip_flag']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Create a DecisionTreeClassifier
model = DecisionTreeClassifier()

# Train the model
print("x_train", X_train);
print("y_train", y_train);

model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

x_train variable      10v_BT      10h_BT      18v_BT      18h_BT      23v_BT  \
195955    250.080002  241.789993  245.039993  237.860001  241.899994
140884    257.410004  252.220001  250.279999  244.570007  243.669998
215423    267.220001  254.679993  270.779999  264.399994  272.390015
189442    260.250000  249.309998  259.679993  248.210007  257.010010
121314    168.259995  116.970001  175.070007  133.770004  181.369995
...              ...         ...         ...         ...         ...
120216    261.260010  251.190002  259.970001  253.220001  254.979996
20188     240.850006  222.880005  249.229996  229.320007  249.580002
178914    264.440002  251.309998  262.480011  251.289993  259.850006
2843      252.320007  238.160004  244.300003  234.110001  238.460007
50805     261.119995  243.399994  262.679993  249.750000  264.920013

variable      36v_BT      36h_BT      89v_BT      89h_BT     166v_BT  \
195955    229.789993  222.429993  205.270004  202.210007  216.029999
140884    225.960007  220.759995  233.800003  230.320007  240.360001
215423    271.410004  266.119995  269.260010  268.079987  265.630005
189442    240.429993  230.059998  215.869995  212.210007  254.229996
121314    181.619995  160.850006  222.130005  210.339996  240.270004
...              ...         ...         ...         ...         ...
120216    236.619995  233.360001  235.770004  234.179993  254.050003
20188     246.320007  229.139999  204.289993  195.389999  213.610001
178914    252.009995  243.600006  240.750000  235.470001  252.419998
2843      218.270004  210.960007  202.779999  198.580002  223.949997
50805     265.720001  255.729996  267.760010  260.779999  274.089996

variable     166h_BT    183-3_BT    183-7_BT
195955    212.000000  245.910004  236.740005
140884    236.759995  246.669998  249.139999
215423    264.160004  252.309998  259.989990
189442    252.889999  249.240005  259.399994
121314    233.520004  246.029999  247.369995
...              ...         ...         ...
120216    253.389999  251.100006  258.470001
20188     208.199997  242.949997  237.649994
178914    248.279999  250.630005  255.580002
2843      223.250000  248.300003  248.330002
50805     270.920013  253.619995  265.459991

[50946 rows x 13 columns]
y_train 195955    2.0
140884    2.0
215423    1.0
189442    2.0
121314    2.0
         ...
120216    2.0
20188     0.0
178914    2.0
2843      0.0
50805     0.0
Name: precip_flag, Length: 50946, dtype: float64

In [28]:
from sklearn.metrics import confusion_matrix

# Create a confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Extract TP, TN, FP, FN for labels 1 and 2
TP_1 = conf_matrix[1, 1]  # True Positive for label 1
TN_1 = conf_matrix[0, 0] + conf_matrix[0, 2] + conf_matrix[2, 0] + conf_matrix[2, 2]  # True Negative for label 1
FP_1 = conf_matrix[0, 1] + conf_matrix[2, 1]  # False Positive for label 1
FN_1 = conf_matrix[1, 0] + conf_matrix[1, 2]  # False Negative for label 1

TP_2 = conf_matrix[2, 2]  # True Positive for label 2
TN_2 = conf_matrix[0, 0] + conf_matrix[0, 1] + conf_matrix[1, 0] + conf_matrix[1, 1]  # True Negative for label 2
FP_2 = conf_matrix[0, 2] + conf_matrix[1, 2]  # False Positive for label 2
FN_2 = conf_matrix[2, 0] + conf_matrix[2, 1]  # False Negative for label 2

# Calculate True Positive Rate (TPR) and False Positive Rate (FPR) for labels 1 and 2
TPR_1 = TP_1 / (TP_1 + FN_1)
FPR_1 = FP_1 / (FP_1 + TN_1)

TPR_2 = TP_2 / (TP_2 + FN_2)
FPR_2 = FP_2 / (FP_2 + TN_2)

# Print the results
print(f"Label 1 - TPR: {TPR_1}, FPR: {FPR_1}")
print(f"Label 2 - TPR: {TPR_2}, FPR: {FPR_2}")

Label 1 - TPR: 0.9301825993555317, FPR: 0.0071642162970346375
Label 2 - TPR: 0.9762101210121013, FPR: 0.05056121923591803

In [ ]:
ocean:
Label 1 - TPR: 0.9655951896559519, FPR: 0.03928282388096869
Label 2 - TPR: 0.9767519652115738, FPR: 0.009592673931960387

land:
Label 1 - TPR: 0.9544333188216514, FPR: 0.07479876160990712
Label 2 - TPR: 0.9471228615863142, FPR: 0.004957062068002513

coast:
Label 1 - TPR: 0.9693877551020408, FPR: 0.05998125585754452
Label 2 - TPR: 0.9377162629757786, FPR: 0.005818786367414797

seaIce:
Label 1 - TPR: 0.928, FPR: 0.002937189335743335
Label 2 - TPR: 0.9830129637907913, FPR: 0.06179775280898876

snow:
Label 1 - TPR: 0.9301825993555317, FPR: 0.0071642162970346375
Label 2 - TPR: 0.9762101210121013, FPR: 0.05056121923591803