In [48]:
import scipy.io
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
file_path = "balanced_ocean_dictionary.mat"
mat_data = scipy.io.loadmat(file_path)
matrix_data = mat_data['dic_ocean'] # for others use dic_land, dic_ice, dic_ocean, dic_coast, dic_sc

# Convert the matrix data to a Pandas DataFrame
df = pd.DataFrame(matrix_data) # load dictionary for different surface type and store it into differet dataframe

In [49]:
rows_to_keep = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 29] # I have put the input features in the rows
#and only the rows with given rows index will be used for our model
df_req = df.iloc[rows_to_keep]
df_req

,0,1,2,3,4,5,6,7,8,9,...,665016,665017,665018,665019,665020,665021,665022,665023,665024,665025
0,159.139999,163.229996,173.520004,173.199997,172.850006,161.529999,169.520004,251.720001,174.279999,162.940002,...,246.119995,246.119995,246.119995,248.289993,248.289993,238.830002,238.880005,238.880005,273.230011,273.230011
1,82.360001,93.809998,95.489998,95.389999,99.669998,91.779999,86.529999,228.470001,98.639999,87.239998,...,228.759995,228.759995,228.759995,231.089996,231.089996,206.399994,206.869995,206.869995,268.589996,268.589996
2,180.250000,178.199997,207.839996,199.899994,203.550003,180.460007,190.589996,257.850006,209.880005,179.479996,...,250.610001,250.610001,250.610001,251.139999,251.139999,244.919998,245.690002,245.690002,273.470001,273.470001
3,105.150002,112.410004,147.869995,135.520004,147.979996,116.930000,116.089996,241.259995,154.910004,107.220001,...,235.149994,235.149994,235.149994,236.449997,236.449997,215.860001,220.389999,220.389999,271.619995,271.619995
4,200.779999,192.550003,247.380005,234.740005,241.990005,197.639999,217.270004,262.940002,250.300003,198.330002,...,255.589996,255.589996,255.589996,255.990005,255.990005,251.119995,253.440002,253.440002,274.119995,274.119995
5,210.179993,203.580002,228.830002,218.279999,224.380005,210.029999,215.809998,262.730011,236.240005,202.610001,...,256.399994,256.399994,256.399994,257.480011,257.480011,252.220001,254.419998,254.419998,274.070007,274.070007
6,140.089996,145.130005,176.770004,161.149994,176.889999,155.649994,148.529999,247.679993,192.380005,136.190002,...,242.550003,242.550003,242.550003,244.669998,244.669998,229.169998,232.600006,232.600006,271.839996,271.839996
7,248.899994,236.720001,279.940002,271.950012,276.170013,244.330002,268.890015,270.790009,277.170013,244.130005,...,267.119995,267.119995,267.119995,268.119995,268.119995,267.420013,267.269989,267.269989,275.820007,275.820007
8,203.179993,191.800003,265.019989,248.270004,263.579987,212.830002,238.479996,262.079987,271.320007,192.009995,...,261.079987,261.079987,261.079987,263.579987,263.579987,257.089996,256.480011,256.480011,274.350006,274.350006
9,266.709991,260.500000,282.350006,284.850006,281.660004,259.309998,285.540009,274.839996,271.850006,278.750000,...,272.200012,272.200012,272.200012,271.220001,271.220001,268.809998,268.359985,268.359985,272.440002,272.440002
10,259.670013,245.949997,283.540009,286.239990,283.269989,252.330002,285.149994,274.010010,272.899994,266.980011,...,270.920013,270.920013,270.920013,269.950012,269.950012,268.170013,267.750000,267.750000,272.190002,272.190002
11,255.710007,254.369995,259.829987,261.769989,264.109985,252.009995,275.589996,253.570007,255.210007,273.619995,...,255.759995,255.759995,255.759995,256.130005,256.130005,252.369995,252.639999,252.639999,251.279999,251.279999
12,263.309998,261.760010,273.809998,274.730011,274.049988,258.869995,281.029999,265.119995,265.850006,284.579987,...,264.700012,264.700012,264.700012,265.209991,265.209991,261.769989,261.140015,261.140015,262.980011,262.980011
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
29,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN

In [50]:
df_req.iloc[13].unique() # This rows give information about precipitation phase. 0 = no_precip, 3= rain, 5= snow

array([0., 5., 3.])

In [51]:
df_req.iloc[13] = df_req.iloc[13].replace({3.0: 1, 5.0: 2}) # Modifying the index so 1 = rain, 2=snow
# we are providing the name to the input features. They are the information measured by the differnt frequencies that
# helps to determine the precipitation phase
variables = ['10v_BT', '10h_BT', '18v_BT', '18h_BT', '23v_BT', '36v_BT', '36h_BT', '89v_BT', '89h_BT', '166v_BT', '166h_BT', '183-3_BT','183-7_BT', 'precip_flag','pr_rate_nearSurf']
df_req.loc[:, 'variable'] = variables
df_req.set_index('variable', inplace=True)
# If you find missing data, delete the entire column. If the data of one input feature is missing, data of other features at
#that instant is of no use
df_req = df_req.dropna(axis=1)
#I am transposing it for the proper visualization
df_tran = df_req.T
df_tran

variable,10v_BT,10h_BT,18v_BT,18h_BT,23v_BT,36v_BT,36h_BT,89v_BT,89h_BT,166v_BT,166h_BT,183-3_BT,183-7_BT,precip_flag,pr_rate_nearSurf
5,161.529999,91.779999,180.460007,116.930000,197.639999,210.029999,155.649994,244.330002,212.830002,259.309998,252.330002,252.009995,258.869995,0.0,0.0
8,174.279999,98.639999,209.880005,154.910004,250.300003,236.240005,192.380005,277.170013,271.320007,271.850006,272.899994,255.210007,265.850006,0.0,0.0
11,171.309998,94.360001,195.630005,130.919998,227.229996,217.020004,159.160004,269.859985,243.660004,288.230011,287.820007,272.239990,281.059998,0.0,0.0
20,168.139999,92.250000,191.369995,128.339996,221.850006,213.169998,156.389999,263.769989,237.240005,282.230011,281.239990,263.570007,273.429993,0.0,0.0
23,171.100006,91.360001,193.529999,125.360001,224.639999,214.699997,151.259995,267.730011,235.309998,289.850006,288.880005,270.600006,281.970001,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
665016,246.119995,228.759995,250.610001,235.149994,255.589996,256.399994,242.550003,267.119995,261.079987,272.200012,270.920013,255.759995,264.700012,1.0,0.0
665017,246.119995,228.759995,250.610001,235.149994,255.589996,256.399994,242.550003,267.119995,261.079987,272.200012,270.920013,255.759995,264.700012,1.0,0.0
665018,246.119995,228.759995,250.610001,235.149994,255.589996,256.399994,242.550003,267.119995,261.079987,272.200012,270.920013,255.759995,264.700012,1.0,0.0
665019,248.289993,231.089996,251.139999,236.449997,255.990005,257.480011,244.669998,268.119995,263.579987,271.220001,269.950012,256.130005,265.209991,1.0,0.0
665020,248.289993,231.089996,251.139999,236.449997,255.990005,257.480011,244.669998,268.119995,263.579987,271.220001,269.950012,256.130005,265.209991,1.0,0.0

Now, you can start training the model. Create the datafrmae like this for the different surface type and evaluate the classifiers for each surface type. At the last, you can concatenate all the dataframe and can train the model on the whole data at once and see whether land surface classification increase model performance or not.

## Here is the Demo code that shows you How I trained xtreme gradient boosting decision tree for the phase prediction

In [33]:
pip install numpy

Requirement already satisfied: numpy in c:\users\aryan\anaconda3\lib\site-packages (1.26.4)
Note: you may need to restart the kernel to use updated packages.

In [34]:
pip install pandas

Requirement already satisfied: pandas in c:\users\aryan\anaconda3\lib\site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\aryan\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aryan\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\aryan\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\aryan\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\aryan\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [35]:
pip install seaborn

Requirement already satisfied: seaborn in c:\users\aryan\anaconda3\lib\site-packages (0.12.2)
Requirement already satisfied: numpy!=1.24.0,>=1.17 in c:\users\aryan\anaconda3\lib\site-packages (from seaborn) (1.26.4)
Requirement already satisfied: pandas>=0.25 in c:\users\aryan\anaconda3\lib\site-packages (from seaborn) (2.1.4)
Requirement already satisfied: matplotlib!=3.6.1,>=3.1 in c:\users\aryan\anaconda3\lib\site-packages (from seaborn) (3.8.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\aryan\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\aryan\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\aryan\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\aryan\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\aryan\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (23.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\aryan\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\aryan\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\aryan\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\aryan\anaconda3\lib\site-packages (from pandas>=0.25->seaborn) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\aryan\anaconda3\lib\site-packages (from pandas>=0.25->seaborn) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\aryan\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.1->seaborn) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [36]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\aryan\anaconda3\lib\site-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in c:\users\aryan\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.3.2 in c:\users\aryan\anaconda3\lib\site-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in c:\users\aryan\anaconda3\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\aryan\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Note: you may need to restart the kernel to use updated packages.

In [37]:
pip install pydotplus

Requirement already satisfied: pydotplus in c:\users\aryan\anaconda3\lib\site-packages (2.0.2)
Requirement already satisfied: pyparsing>=2.0.1 in c:\users\aryan\anaconda3\lib\site-packages (from pydotplus) (3.0.9)
Note: you may need to restart the kernel to use updated packages.

In [38]:
pip install GraphViz

Requirement already satisfied: GraphViz in c:\users\aryan\anaconda3\lib\site-packages (0.20.1)
Note: you may need to restart the kernel to use updated packages.

In [39]:
pip install xgboost

Requirement already satisfied: xgboost in c:\users\aryan\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: numpy in c:\users\aryan\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\aryan\anaconda3\lib\site-packages (from xgboost) (1.11.4)
Note: you may need to restart the kernel to use updated packages.

In [52]:
# Now its time to train the model
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
X = df_tran[['10v_BT', '10h_BT', '18v_BT', '18h_BT', '23v_BT', '36v_BT', '36h_BT', '89v_BT', '89h_BT', '166v_BT', '166h_BT', '183-3_BT', '183-7_BT']]
y = df_tran['precip_flag']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Create a DecisionTreeClassifier
model = DecisionTreeClassifier()

# Train the model
print("x_train", X_train);
print("y_train", y_train);

model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

x_train variable      10v_BT     10h_BT      18v_BT      18h_BT      23v_BT  \
376128    165.330002  98.529999  183.639999  122.000000  198.380005
222245    159.979996  85.190002  177.470001  103.389999  194.389999
653510    169.289993  98.669998  199.839996  144.940002  229.919998
93519     161.020004  85.830002  178.839996  108.519997  199.050003
106603    161.449997  84.169998  180.789993  107.870003  203.559998
...              ...        ...         ...         ...         ...
378647    158.149994  87.860001  178.550003  111.139999  198.229996
328025    166.589996  89.279999  181.000000  108.150002  200.009995
415967    165.419998  95.230003  186.220001  124.750000  206.830002
458755    162.389999  92.000000  185.839996  122.139999  206.880005
384881    162.419998  95.769997  184.660004  122.949997  199.229996

variable      36v_BT      36h_BT      89v_BT      89h_BT     166v_BT  \
376128    212.240005  162.830002  246.610001  221.240005  257.690002
222245    204.539993  134.880005  243.369995  191.610001  269.260010
653510    236.979996  202.000000  271.559998  269.429993  270.589996
93519     204.889999  138.380005  245.240005  198.660004  269.170013
106603    207.520004  140.089996  251.470001  209.419998  273.570007
...              ...         ...         ...         ...         ...
378647    206.940002  145.990005  242.169998  205.940002  255.809998
328025    204.550003  135.100006  248.240005  196.750000  281.950012
415967    216.850006  167.940002  251.899994  230.479996  257.299988
458755    215.869995  165.089996  252.460007  232.500000  263.079987
384881    215.529999  168.520004  248.869995  228.460007  257.260010

variable     166h_BT    183-3_BT    183-7_BT
376128    251.410004  249.309998  256.260010
222245    258.510010  257.649994  267.670013
653510    270.079987  249.380005  261.290009
93519     264.220001  258.690002  267.399994
106603    269.709991  255.029999  268.359985
...              ...         ...         ...
378647    249.169998  246.360001  254.910004
328025    272.579987  272.450012  281.989990
415967    251.919998  248.399994  256.140015
458755    260.239990  249.550003  257.809998
384881    254.850006  244.119995  253.089996

[162733 rows x 13 columns]
y_train 376128    2.0
222245    0.0
653510    1.0
93519     0.0
106603    0.0
         ...
378647    2.0
328025    0.0
415967    1.0
458755    1.0
384881    2.0
Name: precip_flag, Length: 162733, dtype: float64

In [53]:
from sklearn.metrics import confusion_matrix

# Create a confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Extract TP, TN, FP, FN for labels 1 and 2
TP_1 = conf_matrix[1, 1]  # True Positive for label 1
TN_1 = conf_matrix[0, 0] + conf_matrix[0, 2] + conf_matrix[2, 0] + conf_matrix[2, 2]  # True Negative for label 1
FP_1 = conf_matrix[0, 1] + conf_matrix[2, 1]  # False Positive for label 1
FN_1 = conf_matrix[1, 0] + conf_matrix[1, 2]  # False Negative for label 1

TP_2 = conf_matrix[2, 2]  # True Positive for label 2
TN_2 = conf_matrix[0, 0] + conf_matrix[0, 1] + conf_matrix[1, 0] + conf_matrix[1, 1]  # True Negative for label 2
FP_2 = conf_matrix[0, 2] + conf_matrix[1, 2]  # False Positive for label 2
FN_2 = conf_matrix[2, 0] + conf_matrix[2, 1]  # False Negative for label 2

# Calculate True Positive Rate (TPR) and False Positive Rate (FPR) for labels 1 and 2
TPR_1 = TP_1 / (TP_1 + FN_1)
FPR_1 = FP_1 / (FP_1 + TN_1)

TPR_2 = TP_2 / (TP_2 + FN_2)
FPR_2 = FP_2 / (FP_2 + TN_2)

# Print the results
print(f"Label 1 - TPR: {TPR_1}, FPR: {FPR_1}")
print(f"Label 2 - TPR: {TPR_2}, FPR: {FPR_2}")

Label 1 - TPR: 0.9655951896559519, FPR: 0.03928282388096869
Label 2 - TPR: 0.9767519652115738, FPR: 0.009592673931960387